ens_activity:
    path:     /
    defaults: { _controller: "AppBundle:Activity:index" }

ens_activity_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Activity:show" }

ens_activity_new:
    path:     /new
    defaults: { _controller: "AppBundle:Activity:new" }

ens_activity_create:
    path:     /create
    defaults: { _controller: "AppBundle:Activity:create" }
    methods:  POST

ens_activity_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Activity:edit" }

ens_activity_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Activity:update" }
    methods:  [POST, PUT]

ens_activity_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Activity:delete" }
    methods:  [POST, DELETE]
