ens_actor:
    path:     /
    defaults: { _controller: "AppBundle:Actor:index" }

ens_actor_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Actor:show" }

ens_actor_new:
    path:     /new
    defaults: { _controller: "AppBundle:Actor:new" }

ens_actor_create:
    path:     /create
    defaults: { _controller: "AppBundle:Actor:create" }
    methods:  POST

ens_actor_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Actor:edit" }

ens_actor_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Actor:update" }
    methods:  [POST, PUT]

ens_actor_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Actor:delete" }
    methods:  [POST, DELETE]
