ens_equipment:
    path:     /
    defaults: { _controller: "AppBundle:Equipment:index" }

ens_equipment_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Equipment:show" }

ens_equipment_new:
    path:     /new
    defaults: { _controller: "AppBundle:Equipment:new" }

ens_equipment_create:
    path:     /create
    defaults: { _controller: "AppBundle:Equipment:create" }
    methods:  POST

ens_equipment_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Equipment:edit" }

ens_equipment_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Equipment:update" }
    methods:  [POST, PUT]

ens_equipment_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Equipment:delete" }
    methods:  [POST, DELETE]
